export const industryType = [
    "BPO/Call Centre",
    "Analytics/KPO/Research",
    "IT Services & Consulting",
    "Electronic Components/ Semiconductors",
    "Electronics Manufacturing",
    "Emerging Technologies",
    "Internet",
    "Software Product",
    "Banking",
    "Financial services",
    "Fintech/Payments",
    "Insurance",
    "Investment Banking / Venture capital/ Private equity",
    "NBFC",
    "Education/Training",
    "E-Learning / EdTech",
    "Auto components",
    "Automobile",
    "Building Material",
    "Chemicals",
    "Defence & Aerospace",
    "Electrical Equipment",
    "Fertilizers / Pesticides/ Agro Chemicals",
    "Industrial Automation",
    "Industrial Equipment/ Machinery",
    "Iron & Steel",
    "Metal & Mining",
    "Packaging & Containers",
    "Petrochemicals/ Plastics/ Rubber",
    "Pulp& Paper",
    "Aviation",
    "Courier/ Logistics",
    "Engineering & Construction",
    "Oil & Gas",
    "Ports & Shipping",
    "Power",
    "Railways",
    "Real Estate",
    "Urban Transport",
    "Water treatment/ Waste management",
    "Beauty & Personal care",
    "Beverage",
    "Consumer electronics & Appliances",
    "Fitness & wellness",
    "FMCG",
    "Food processing",
    "Furniture & Furnishing",
    "Gem & Jewelry",
    "Hotels & Restaurants",
    "Leather",
    "Retail",
    "Textile & Tourism",
    "Biotechnology",
    "Clinical Research/ Contract research",
    "Medical devices & Equipment",
    "Medical services / Hospitals",
    "Pharmaceutical & life science",
    "Advertising & Marketing",
    "Animation & VFX",
    "Events/ Live entertainment",
    "Film/ Music/ Entertainment",
    "Gaming",
    "Printing & Publishing",
    "Sports/ Leisure & Recreation",
    "Telecom/ ISP",
    "TV/ Radio",
    "Accounting/Auditing",
    "Architecture/ Interior Design",
    "Content development/ Language",
    "Design",
    "Fecility management services",
    "Legal",
    "Management consulting",
    "Recruitment / Staffing",
    "Agriculture/ Forestry/ Fishing",
    "Government/ Public Administration",
    "Import & Export",
    "Miscellaneous",
    "NGO/ Social services/ Indusrty",
];
