export const Qualification = [
    "Engineering",
    "Hotel Management",
    "Medical",
    "Journalism / Mass Communication",
    "UG Popular course",
    "Vocational-Training",
    "B.Arch",
    "B.Des",
    "B.Ed",
    "B.EI.Ed",
    "B.P.Ed",
    "B.Pharma",
    "B.Sc",
    "B.Tech / B.E",
    "B.U.M.S",
    "BAMS",
    "BCA",
    "BDS",
    "BFA",
    "BHM",
    "BHMCT",
    "BHMS",
    "BVSC",
    "Diploma",
    "LLB",
    "MBBS",
    "Other Graduate",
    "Computers Degree / Diploma",
    "Management",
    "Journalism/ Mass Communication",
    "M.Tech",
    "MBA/ PGDM",
    "PG Popular Course",
    "PR/ Advertising",
    "CA",
    "CS",
    "DM",
    "ICWA (CMA)",
    "Integrated PG",
    "LLM",
    "MA",
    "M.Arch",
    "M.Ch",
    "M.Com",
    "M.Des",
    "M.Ed",
    "M.Pharma",
    "M.Tech",
    "MBA / PGDM",
    "MCA",
    "MCM",
    "MDS",
    "MFA",
    "MS/ M.Sc (Science)",
    "MVSC",
    "Medical -MS/ MD",
    "PG Diploma",
    "Other Post Graduate",
]